version: '3.8'

services:
  webapi:
    build: .
    container_name: dotnet-webapi
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskManagementDb;User=sa;Password=YourPassword123!;TrustServerCertificate=true
      - JwtSettings__Issuer=http://localhost:5000
      - JwtSettings__Audience=http://localhost:5000
    depends_on:
      - db
    networks:
      - webapi-network

  # Optional: Add a SQL Server database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dotnet-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - webapi-network

volumes:
  db_data:

networks:
  webapi-network:
    driver: bridge
